-- INSERT INTO recipes (title, prep_time, ready_in, instructions) VALUES 
    -- ('chicken and rice', '30 m', '2 h', '(1) Put water and rice in rice cooker., (2) Cook chicken in skillet until brown.')
    -- ('chicken salad', '15 m', '30 m', '(1) Cook the chicken. (2) Wash and cut the vegetables, (3) Combine ingredients.'),
    -- ('fish taco', '30 m', '1 h', '(1) Coat fish with batter and fry. (2) Chop lettuce and tomatoes. (3) Assemble tacos on tortilla.');
    -- ('orange chicken', '30 m', '2 h', '(1) Cut chicken into small pieces. (2) Coat chicken with eggs and flour. (3) Fry chicken. (4) Make orange glaze. (5) Coat fried chicken with glaze.')
    -- ('string beans with bacon', '30 m', '2 h',)

INSERT INTO recipes(title) VALUES
('chicken and rice'),
('chicken salad'),
('fish taco'),
('orange chicken'),
('string beans with bacon'),
('beef stew'),
('strawberry banana smoothie'),
('lemon chicken'),
('lemon fish'),
('vegetable stew'),
('omelette'),
('tofu with string beans'),
('tomato beef'),
('mushroom chicken'),
('supberbowl nachos'),
('tuna sandwich'),
('carbonara'),
('cheesecake'),
('breakfast delight'),
('tropical smoothie');



INSERT INTO ingredients (ingredient_name) VALUES
('chicken'),
('fish'),
('bacon'),
('egg'),
('beef'),
('apple'),
('banana'),
('orange'),
('lemon'),
('tomato'),
('lettuce'),
('spinach'),
('onion'),
('carrot'),
('celery'),
('mushroom'), 
('rice'),
('cheese'),
('string beans'),
('tofu');



-- INSERT INTO recipe_ingredients(recipe_id, ingredient_id, measurement) VALUES
-- (1, 1, '1 lb'),
-- (1, 6, '1 c'),
-- (2, 1, '1 c'),
-- (2, 3, '2 c'),
-- (2, 4, '1/2 c'),
-- (3, 2, '2 c'),
-- (3, 3, '3 c'),
-- (3, 7, '10 pieces');

INSERT INTO recipe_ingredients(recipe_id, ingredient_id) VALUES
(1, 1),
(1, 17),
(1, 13),
(2, 1),
(2, 11),
(2, 10),
(3, 2),
(3, 10),
(3, 11),
(4, 1),
(4, 8),
(4, 4),
(5, 3),
(5, 19),
(5, 13),
(6, 5),
(6, 14),
(6, 13),
(6, 10),
(7, 7),
(8, 1),
(8, 9),
(9, 2),
(9, 9),
(10, 10),
(10, 13),
(10, 14),
(10, 15),
(10, 16),
(11, 4),
(11, 13),
(11, 3),
(12, 20),
(12, 19),
(12, 13),
(13, 10),
(13, 5),
(13, 13),
(14, 1),
(14, 16),
(14, 13),
(15, 18),
(16, 2),
(16, 15),
(16, 13),
(17, 4),
(17, 3),
(19, 3),
(19, 4),
(19, 10),
(19, 12),
(19, 16),
(20, 7),
(20, 8);
